// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prototype_Curio_stagemarkt.Data;

#nullable disable

namespace Prototype_Curio_stagemarkt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240923100404_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.AdminClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fedde",
                            Password = "osgriDosmCm7P/3BNm4Wz4flocJmwfl3ZaO3UGd5zpk=:uq9fLAcLag1Q57s+6wssTw==:10000:SHA512"
                        });
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CvFilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Motivation")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudentId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LearningPathId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Specialization")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LearningPathId");

                    b.HasIndex("LevelId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Breda",
                            Description = "Over Ons:\r\n\r\nWij zijn Company1, een dynamisch softwareontwikkelingsbedrijf dat innovatieve oplossingen biedt voor complexe problemen.\n Onze expertise ligt in het creëren van op maat gemaakte softwaretoepassingen die de bedrijfsprocessen van onze klanten optimaliseren.\n Van mobiele apps tot uitgebreide webplatformen, wij brengen ideeën tot leven met cutting-edge technologie en een focus op kwaliteit.\n Ons team bestaat uit gepassioneerde ontwikkelaars, ontwerpers en projectmanagers die samen streven naar uitmuntendheid in elk project.\r\n\r\nWat We Zoeken in een Stagiair:\r\n\r\nWij zijn op zoek naar getalenteerde en leergierige stagiaires die onze passie voor technologie delen. Als stagiair bij [Bedrijfsnaam] krijg je de kans om deel uit te maken van een innovatief team en mee te werken aan uitdagende projecten.\r\n\r\n**Opleidingsachtergrond:**\r\n- Je volgt een opleiding in Informatica, Software Engineering, of een gerelateerde technische studie.\r\n- Basiskennis van programmeertalen zoals Java, Python, of JavaScript is gewenst.\r\n- Bekendheid met softwareontwikkelingsmethodologieën, zoals Agile, is een pluspunt.\r\n\r\n**Karaktereigenschappen:**\r\n- **Proactief:** Je neemt initiatief en bent niet bang om met nieuwe ideeën te komen.\r\n- **Leergierig:** Je hebt een sterke drang om nieuwe vaardigheden te leren en jezelf voortdurend te verbeteren.\r\n- **Teamplayer:** Je werkt graag in teamverband en kunt goed communiceren.\r\n- Oog voor detail: Je hebt een nauwkeurige aanpak en streeft naar hoge kwaliteit in je werk.\nBij [Bedrijfsnaam] geloven we in het bieden van een omgeving waar stagiaires kunnen groeien en waardevolle ervaring kunnen opdoen in de wereld van softwareontwikkeling. \nAls je klaar bent voor een uitdaging en een passie hebt voor technologie, dan kijken we ernaar uit om van je te horen!",
                            EmailAddress = "Company1@hotmail.nl",
                            IsOpen = true,
                            LearningPathId = 1,
                            LevelId = 1,
                            Name = "Company1",
                            Password = "r8do599o6G59gmyD23axf3cgUG9FpUIBl/WXsuVL3wE=:wqWWrutJX54qazxDK4CUNQ==:10000:SHA512",
                            Phone = "123-456-7890",
                            Specialization = "Native",
                            Street = "123 Main Street"
                        },
                        new
                        {
                            Id = 2,
                            City = "Tilburg",
                            Description = "Over Ons:\r\n\r\nWij zijn Company2, een dynamisch softwareontwikkelingsbedrijf dat innovatieve oplossingen biedt voor complexe problemen.\n Onze expertise ligt in het creëren van op maat gemaakte softwaretoepassingen die de bedrijfsprocessen van onze klanten optimaliseren.\n Van mobiele apps tot uitgebreide webplatformen, wij brengen ideeën tot leven met cutting-edge technologie en een focus op kwaliteit.\n Ons team bestaat uit gepassioneerde ontwikkelaars, ontwerpers en projectmanagers die samen streven naar uitmuntendheid in elk project.\r\n\r\nWat We Zoeken in een Stagiair:\r\n\r\nWij zijn op zoek naar getalenteerde en leergierige stagiaires die onze passie voor technologie delen. Als stagiair bij [Bedrijfsnaam] krijg je de kans om deel uit te maken van een innovatief team en mee te werken aan uitdagende projecten.\r\n\r\n**Opleidingsachtergrond:**\r\n- Je volgt een opleiding in Informatica, Software Engineering, of een gerelateerde technische studie.\r\n- Basiskennis van programmeertalen zoals Java, Python, of JavaScript is gewenst.\r\n- Bekendheid met softwareontwikkelingsmethodologieën, zoals Agile, is een pluspunt.\r\n\r\n**Karaktereigenschappen:**\r\n- **Proactief:** Je neemt initiatief en bent niet bang om met nieuwe ideeën te komen.\r\n- **Leergierig:** Je hebt een sterke drang om nieuwe vaardigheden te leren en jezelf voortdurend te verbeteren.\r\n- **Teamplayer:** Je werkt graag in teamverband en kunt goed communiceren.\r\n- Oog voor detail: Je hebt een nauwkeurige aanpak en streeft naar hoge kwaliteit in je werk.\nBij [Bedrijfsnaam] geloven we in het bieden van een omgeving waar stagiaires kunnen groeien en waardevolle ervaring kunnen opdoen in de wereld van softwareontwikkeling. \nAls je klaar bent voor een uitdaging en een passie hebt voor technologie, dan kijken we ernaar uit om van je te horen!",
                            EmailAddress = "Company2@hotmail.nl",
                            IsOpen = true,
                            LearningPathId = 2,
                            LevelId = 2,
                            Name = "Company2",
                            Password = "OnouLchWRiLjK1BrS3BAPVOvf4ZMixSyj+kucD8s214=:oBp/bku5OoXGOfG36ZdsQQ==:10000:SHA512",
                            Phone = "987-654-3210",
                            Specialization = "Native",
                            Street = "456 Oak Avenue"
                        },
                        new
                        {
                            Id = 3,
                            City = "Roosendaal",
                            Description = "Over Ons:\r\n\r\nWij zijn Company3, een dynamisch softwareontwikkelingsbedrijf dat innovatieve oplossingen biedt voor complexe problemen.\n Onze expertise ligt in het creëren van op maat gemaakte softwaretoepassingen die de bedrijfsprocessen van onze klanten optimaliseren.\n Van mobiele apps tot uitgebreide webplatformen, wij brengen ideeën tot leven met cutting-edge technologie en een focus op kwaliteit.\n Ons team bestaat uit gepassioneerde ontwikkelaars, ontwerpers en projectmanagers die samen streven naar uitmuntendheid in elk project.\r\n\r\nWat We Zoeken in een Stagiair:\r\n\r\nWij zijn op zoek naar getalenteerde en leergierige stagiaires die onze passie voor technologie delen. Als stagiair bij [Bedrijfsnaam] krijg je de kans om deel uit te maken van een innovatief team en mee te werken aan uitdagende projecten.\r\n\r\n**Opleidingsachtergrond:**\r\n- Je volgt een opleiding in Informatica, Software Engineering, of een gerelateerde technische studie.\r\n- Basiskennis van programmeertalen zoals Java, Python, of JavaScript is gewenst.\r\n- Bekendheid met softwareontwikkelingsmethodologieën, zoals Agile, is een pluspunt.\r\n\r\n**Karaktereigenschappen:**\r\n- **Proactief:** Je neemt initiatief en bent niet bang om met nieuwe ideeën te komen.\r\n- **Leergierig:** Je hebt een sterke drang om nieuwe vaardigheden te leren en jezelf voortdurend te verbeteren.\r\n- **Teamplayer:** Je werkt graag in teamverband en kunt goed communiceren.\r\n- Oog voor detail: Je hebt een nauwkeurige aanpak en streeft naar hoge kwaliteit in je werk.\nBij [Bedrijfsnaam] geloven we in het bieden van een omgeving waar stagiaires kunnen groeien en waardevolle ervaring kunnen opdoen in de wereld van softwareontwikkeling. \nAls je klaar bent voor een uitdaging en een passie hebt voor technologie, dan kijken we ernaar uit om van je te horen!",
                            EmailAddress = "Company3@hotmail.nl",
                            IsOpen = true,
                            LearningPathId = 1,
                            LevelId = 3,
                            Name = "Company3",
                            Password = "z33Tq+e14kcLEcTEmxfuwHnqoxctP+8hRux6fTwaEzU=:ijjZyZfem5pIcHUro7kW2A==:10000:SHA512",
                            Phone = "555-123-4567",
                            Specialization = "Native",
                            Street = "789 Pine Road"
                        },
                        new
                        {
                            Id = 4,
                            City = "Genk",
                            Description = "Over Ons:\r\n\r\nWij zijn Company4, een dynamisch softwareontwikkelingsbedrijf dat innovatieve oplossingen biedt voor complexe problemen. Onze expertise ligt in het creëren van op maat gemaakte softwaretoepassingen die de bedrijfsprocessen van onze klanten optimaliseren. Van mobiele apps tot uitgebreide webplatformen, wij brengen ideeën tot leven met cutting-edge technologie en een focus op kwaliteit. Ons team bestaat uit gepassioneerde ontwikkelaars, ontwerpers en projectmanagers die samen streven naar uitmuntendheid in elk project.\r\n\r\nWat We Zoeken in een Stagiair:\r\n\r\nWij zijn op zoek naar getalenteerde en leergierige stagiaires die onze passie voor technologie delen. Als stagiair bij [Bedrijfsnaam] krijg je de kans om deel uit te maken van een innovatief team en mee te werken aan uitdagende projecten.\r\n\r\n**Opleidingsachtergrond:**\r\n- Je volgt een opleiding in Informatica, Software Engineering, of een gerelateerde technische studie.\r\n- Basiskennis van programmeertalen zoals Java, Python, of JavaScript is gewenst.\r\n- Bekendheid met softwareontwikkelingsmethodologieën, zoals Agile, is een pluspunt.\r\n\r\n**Karaktereigenschappen:**\r\n- **Proactief:** Je neemt initiatief en bent niet bang om met nieuwe ideeën te komen.\r\n- **Leergierig:** Je hebt een sterke drang om nieuwe vaardigheden te leren en jezelf voortdurend te verbeteren.\r\n- **Teamplayer:** Je werkt graag in teamverband en kunt goed communiceren.\r\n- Oog voor detail: Je hebt een nauwkeurige aanpak en streeft naar hoge kwaliteit in je werk.\r\n\r\nBij [Bedrijfsnaam] geloven we in het bieden van een omgeving waar stagiaires kunnen groeien en waardevolle ervaring kunnen opdoen in de wereld van softwareontwikkeling. Als je klaar bent voor een uitdaging en een passie hebt voor technologie, dan kijken we ernaar uit om van je te horen!",
                            EmailAddress = "Company4@hotmail.nl",
                            IsOpen = true,
                            LearningPathId = 2,
                            LevelId = 1,
                            Name = "Company4",
                            Password = "kJ7FZVt7XOyqjgE0xvjxTfr8FTouetjxCO2DKDUZwJg=:D0SJU6VJ81IVOZVIZlZdpQ==:10000:SHA512",
                            Phone = "555-123-4567",
                            Specialization = "Web",
                            Street = "799 Pine Road"
                        },
                        new
                        {
                            Id = 5,
                            City = "Breda",
                            Description = "Over Ons:\r\n\r\nWij zijn Company5, een dynamisch softwareontwikkelingsbedrijf dat innovatieve oplossingen biedt voor complexe problemen. Onze expertise ligt in het creëren van op maat gemaakte softwaretoepassingen die de bedrijfsprocessen van onze klanten optimaliseren. Van mobiele apps tot uitgebreide webplatformen, wij brengen ideeën tot leven met cutting-edge technologie en een focus op kwaliteit. Ons team bestaat uit gepassioneerde ontwikkelaars, ontwerpers en projectmanagers die samen streven naar uitmuntendheid in elk project.\r\n\r\nWat We Zoeken in een Stagiair:\r\n\r\nWij zijn op zoek naar getalenteerde en leergierige stagiaires die onze passie voor technologie delen. Als stagiair bij [Bedrijfsnaam] krijg je de kans om deel uit te maken van een innovatief team en mee te werken aan uitdagende projecten.\r\n\r\n**Opleidingsachtergrond:**\r\n- Je volgt een opleiding in Informatica, Software Engineering, of een gerelateerde technische studie.\r\n- Basiskennis van programmeertalen zoals Java, Python, of JavaScript is gewenst.\r\n- Bekendheid met softwareontwikkelingsmethodologieën, zoals Agile, is een pluspunt.\r\n\r\n**Karaktereigenschappen:**\r\n- **Proactief:** Je neemt initiatief en bent niet bang om met nieuwe ideeën te komen.\r\n- **Leergierig:** Je hebt een sterke drang om nieuwe vaardigheden te leren en jezelf voortdurend te verbeteren.\r\n- **Teamplayer:** Je werkt graag in teamverband en kunt goed communiceren.\r\n- Oog voor detail: Je hebt een nauwkeurige aanpak en streeft naar hoge kwaliteit in je werk.\r\n\r\nBij [Bedrijfsnaam] geloven we in het bieden van een omgeving waar stagiaires kunnen groeien en waardevolle ervaring kunnen opdoen in de wereld van softwareontwikkeling. Als je klaar bent voor een uitdaging en een passie hebt voor technologie, dan kijken we ernaar uit om van je te horen!",
                            EmailAddress = "Company5@hotmail.nl",
                            IsOpen = true,
                            LearningPathId = 1,
                            LevelId = 2,
                            Name = "Company5",
                            Password = "AECsSI2IxqtBfHWWLiVBIcQ2PHnOBIOHjiWWGQ6ZUCI=:nj7MIos+lAeKKOUuHuAnPw==:10000:SHA512",
                            Phone = "555-123-4568",
                            Specialization = "Web",
                            Street = "749 Pine Road"
                        },
                        new
                        {
                            Id = 6,
                            City = "Rotterdam",
                            Description = "Over Ons:\r\n\r\nWij zijn Company5, een dynamisch softwareontwikkelingsbedrijf dat innovatieve oplossingen biedt voor complexe problemen. Onze expertise ligt in het creëren van op maat gemaakte softwaretoepassingen die de bedrijfsprocessen van onze klanten optimaliseren. Van mobiele apps tot uitgebreide webplatformen, wij brengen ideeën tot leven met cutting-edge technologie en een focus op kwaliteit. Ons team bestaat uit gepassioneerde ontwikkelaars, ontwerpers en projectmanagers die samen streven naar uitmuntendheid in elk project.\r\n\r\nWat We Zoeken in een Stagiair:\r\n\r\nWij zijn op zoek naar getalenteerde en leergierige stagiaires die onze passie voor technologie delen. Als stagiair bij [Bedrijfsnaam] krijg je de kans om deel uit te maken van een innovatief team en mee te werken aan uitdagende projecten.\r\n\r\n**Opleidingsachtergrond:**\r\n- Je volgt een opleiding in Informatica, Software Engineering, of een gerelateerde technische studie.\r\n- Basiskennis van programmeertalen zoals Java, Python, of JavaScript is gewenst.\r\n- Bekendheid met softwareontwikkelingsmethodologieën, zoals Agile, is een pluspunt.\r\n\r\n**Karaktereigenschappen:**\r\n- **Proactief:** Je neemt initiatief en bent niet bang om met nieuwe ideeën te komen.\r\n- **Leergierig:** Je hebt een sterke drang om nieuwe vaardigheden te leren en jezelf voortdurend te verbeteren.\r\n- **Teamplayer:** Je werkt graag in teamverband en kunt goed communiceren.\r\n- Oog voor detail: Je hebt een nauwkeurige aanpak en streeft naar hoge kwaliteit in je werk.\r\n\r\nBij [Bedrijfsnaam] geloven we in het bieden van een omgeving waar stagiaires kunnen groeien en waardevolle ervaring kunnen opdoen in de wereld van softwareontwikkeling. Als je klaar bent voor een uitdaging en een passie hebt voor technologie, dan kijken we ernaar uit om van je te horen!",
                            EmailAddress = "Company5@hotmail.nl",
                            IsOpen = true,
                            LearningPathId = 2,
                            LevelId = 3,
                            Name = "Company5",
                            Password = "Y53cL+NRdK3qnZq4S9gUm3WQLcfXQ4vtezjy8WzNXlI=:Nzew8Kf3p4pz8dKgF1gGXQ==:10000:SHA512",
                            Phone = "555-123-4568",
                            Specialization = "Web",
                            Street = "749 Pine Road"
                        });
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Native"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Web"
                        },
                        new
                        {
                            Id = 3,
                            Name = "FrontEnd"
                        });
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.FavoriteCompany", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CompanyId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("FavoriteCompanies");
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.InternschipTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("InternschipTeachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laurens",
                            Password = "PGhbu6lDkjFewDIQPbFtJaMR4FABC13oVsoEj2tTtg4=:j45AuD9xCLmSbXbzPXVlkg==:10000:SHA512"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kiki",
                            Password = "pF2hdItMsfYLOgxr2ApszDTfjyXT7f7PMijBw/xsLCk=:bTvhCarYAnpqP/dH2PxUag==:10000:SHA512"
                        });
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.LearningPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LearningPaths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BOL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BBL"
                        });
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeLevel = 2
                        },
                        new
                        {
                            Id = 2,
                            GradeLevel = 3
                        },
                        new
                        {
                            Id = 3,
                            GradeLevel = 4
                        });
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAdress")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<int?>("InternschipTeacherId")
                        .HasColumnType("int");

                    b.Property<int?>("InternshipTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Specialization")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("InternschipTeacherId");

                    b.HasIndex("InternshipTeacherId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAdress = "student1@example.com",
                            InternshipTeacherId = 1,
                            Name = "Max",
                            Password = "prbkM48EHLICaDJDm7/m+PVYsc0IpTt6KrYOa9xq6sI=:pz3poN67286ThsAM/NxaOw==:10000:SHA512",
                            Specialization = "Native"
                        },
                        new
                        {
                            Id = 2,
                            EmailAdress = "student2@example.com",
                            InternshipTeacherId = 2,
                            Name = "JJ",
                            Password = "UlzsL6mXkYUwrrEu38S9ZppBB7D6an8w1Cudp8WfZzU=:TaFZrRAD3K3bc6GFdfCSXA==:10000:SHA512",
                            Specialization = "Native"
                        },
                        new
                        {
                            Id = 3,
                            EmailAdress = "student1@example.com",
                            InternshipTeacherId = 1,
                            Name = "Krijn",
                            Password = "4ZVUK4zF0RZ8SMnxVDmeXqvl54alHe5KIu2Ig39fH9c=:GTzAKp1UBK/ZrZGBSUCiGQ==:10000:SHA512",
                            Specialization = "Native"
                        },
                        new
                        {
                            Id = 4,
                            EmailAdress = "student2@example.com",
                            InternshipTeacherId = 2,
                            Name = "Luna",
                            Password = "O6TtI7vz5vlry7Ynmwvh3xR17X1tH85IY/NhwDB/tM8=:etx2epML6z0vfJS/iutKOw==:10000:SHA512",
                            Specialization = "Native"
                        },
                        new
                        {
                            Id = 5,
                            EmailAdress = "student1@example.com",
                            InternshipTeacherId = 1,
                            Name = "Wiardi",
                            Password = "dkLbcdtllxln1HL4bgLZGx40Cnriiv8tnG9AosSmsKE=:moPShJDPBYf9huNtXopUhw==:10000:SHA512",
                            Specialization = "Native"
                        },
                        new
                        {
                            Id = 6,
                            EmailAdress = "student2@example.com",
                            InternshipTeacherId = 2,
                            Name = "Nigel",
                            Password = "HVNZhge1Q+S6gRaSe/U6WG2DI3otLQ1ULjV80faRQ4k=:BommHdQzvmdwuJOVumBKyw==:10000:SHA512",
                            Specialization = "Native"
                        },
                        new
                        {
                            Id = 7,
                            EmailAdress = "student1@example.com",
                            InternshipTeacherId = 1,
                            Name = "Kelvin",
                            Password = "tWjkLcFvyFsKC3eWPexQb+IVF5MUshRRSXQilVPj+ac=:15DH4f22x0iZRtq8tO91Ow==:10000:SHA512",
                            Specialization = "Native"
                        },
                        new
                        {
                            Id = 8,
                            EmailAdress = "student2@example.com",
                            InternshipTeacherId = 1,
                            Name = "Jonathan",
                            Password = "eU7096WmPBZHWI4mpqWx4BUxX394Gepddtynh0coXBo=:DcyIZhfCDWbG0039S60GGQ==:10000:SHA512",
                            Specialization = "Native"
                        },
                        new
                        {
                            Id = 9,
                            EmailAdress = "student1@example.com",
                            InternshipTeacherId = 1,
                            Name = "Brent",
                            Password = "Rgnue62sqmxGU3brqjiYz2Cce8Owqo5YFbt6MHo91kU=:DkjcfRIAlMOS5Ww7idepgg==:10000:SHA512",
                            Specialization = "Native"
                        },
                        new
                        {
                            Id = 10,
                            EmailAdress = "student2@example.com",
                            InternshipTeacherId = 2,
                            Name = "Simon",
                            Password = "NM15kZkXy/I2RIXf3fRmwWIuJZgt5QaYMQvORNFpJdg=:AXdcWBswwsBDHNRoMzElYg==:10000:SHA512",
                            Specialization = "Native"
                        });
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("IntershipTeacherId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompany")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("IntershipTeacherId");

                    b.HasIndex("StudentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            IsCompany = true
                        },
                        new
                        {
                            Id = 2,
                            IsCompany = false,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsCompany = false,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            IsCompany = true
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 5,
                            IsCompany = true
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 6,
                            IsCompany = true
                        },
                        new
                        {
                            Id = 7,
                            AdminId = 1,
                            IsCompany = false
                        },
                        new
                        {
                            Id = 8,
                            IntershipTeacherId = 1,
                            IsCompany = false
                        },
                        new
                        {
                            Id = 9,
                            IsCompany = false,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 10,
                            IntershipTeacherId = 2,
                            IsCompany = false
                        });
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.WorkHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("WorkHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 8,
                            Status = 0,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 9, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            HoursWorked = 4,
                            Status = 0,
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.Application", b =>
                {
                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.Company", "Company")
                        .WithMany("Applications")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.Student", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.Company", b =>
                {
                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.LearningPath", "LearningPath")
                        .WithMany("Companies")
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.Level", "Level")
                        .WithMany("Companies")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningPath");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.FavoriteCompany", b =>
                {
                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.Company", "Company")
                        .WithMany("FavoriteCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.Student", "Student")
                        .WithMany("FavoriteCompanies")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.Student", b =>
                {
                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.InternschipTeacher", null)
                        .WithMany("Students")
                        .HasForeignKey("InternschipTeacherId");

                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.InternschipTeacher", "InternschipTeacher")
                        .WithMany()
                        .HasForeignKey("InternshipTeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InternschipTeacher");
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.User", b =>
                {
                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.AdminClass", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.InternschipTeacher", "Interschip")
                        .WithMany()
                        .HasForeignKey("IntershipTeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");

                    b.Navigation("Company");

                    b.Navigation("Interschip");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.WorkHour", b =>
                {
                    b.HasOne("Prototype_Curio_stagemarkt.Data.Models.Student", "Student")
                        .WithMany("workHours")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.Company", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("FavoriteCompanies");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.InternschipTeacher", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.LearningPath", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.Level", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Prototype_Curio_stagemarkt.Data.Models.Student", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("FavoriteCompanies");

                    b.Navigation("workHours");
                });
#pragma warning restore 612, 618
        }
    }
}
